caracteristiques_personnages = {
    "Harry Potter": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Noirs",
        "lunettes": True,
        "baguette_particuliere": True,
        "animal": "Hibou",
        "professeur": False,
        "sang": "Mélé",
        "role": "Élève, héros",
        "trait_distinctif": "Cicatrice",
        "moralite": "Gentil",
        "famille": "Potter"
    },
    "Hermione Granger": {
        "maison": "Gryffondor",
        "genre": "F",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Chat",
        "professeur": False,
        "sang": "Moldus",
        "role": "Élève, intelligente",
        "trait_distinctif": "Toujours un livre à la main",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Ron Weasley": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Rat",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, ami de Harry",
        "trait_distinctif": "A peur des araignées",
        "moralite": "Gentil",
        "famille": "Weasley"
    },
    "Draco Malfoy": {
        "maison": "Serpentard",
        "genre": "H",
        "cheveux": "Blonds",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, rival de Harry",
        "trait_distinctif": "Père est un Mangemort",
        "moralite": "Méchant",
        "famille": "Malfoy"
    },
    "Luna Lovegood": {
        "maison": "Serdaigle",
        "genre": "F",
        "cheveux": "Blonds",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Inconnu",
        "role": "Élève, excentrique",
        "trait_distinctif": "Croit aux créatures magiques invisibles",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Neville Londubat": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Crapaud",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, timide",
        "trait_distinctif": "Devenu professeur de botanique",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Ginny Weasley": {
        "maison": "Gryffondor",
        "genre": "F",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, sœur de Ron",
        "trait_distinctif": "Joueuse de Quidditch (attrapeur)",
        "moralite": "Gentil",
        "famille": "Weasley"
    },
    "Fred Weasley": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Farceur, jumeau",
        "trait_distinctif": "Propriétaire de la boutique de farces",
        "moralite": "Gentil",
        "famille": "Weasley"
    },
    "George Weasley": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Farceur, jumeau",
        "trait_distinctif": "A perdu une oreille",
        "moralite": "Gentil",
        "famille": "Weasley"
    },
    "Severus Rogue": {
        "maison": "Serpentard",
        "genre": "H",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": True,
        "sang": "Pur",
        "role": "Professeur, directeur",
        "trait_distinctif": "Ancien Mangemort, amoureux de Lily Potter",
        "moralite": "Ambigu",
        "famille": "N/A"
    },
    "Minerva McGonagall": {
        "maison": "Gryffondor",
        "genre": "F",
        "cheveux": "Noirs",
        "lunettes": True,
        "baguette_particuliere": True,
        "animal": "Chat",
        "professeur": True,
        "sang": "Pur",
        "role": "Professeur, directrice",
        "trait_distinctif": "Peut se transformer en chat",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Albus Dumbledore": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Argentés",
        "lunettes": True,
        "baguette_particuliere": True,
        "animal": "Phénix",
        "professeur": True,
        "sang": "Pur",
        "role": "Directeur de Poudlard",
        "trait_distinctif": "Aime les bonbons et les énigmes",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Rubeus Hagrid": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Noirs/barbe",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Chien",
        "professeur": True,
        "sang": "Mélé",
        "role": "Garde-chasse",
        "trait_distinctif": "Demi-géant, adore les créatures magiques",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Sirius Black": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Chien",
        "professeur": False,
        "sang": "Pur",
        "role": "Parrain de Harry",
        "trait_distinctif": "Animagus (chien noir)",
        "moralite": "Gentil",
        "famille": "Black"
    },
    "Remus Lupin": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": True,
        "sang": "Mélé",
        "role": "Professeur, loup-garou",
        "trait_distinctif": "Transformé en loup-garou",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Bellatrix Lestrange": {
        "maison": "Serpentard",
        "genre": "F",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Mangemort",
        "trait_distinctif": "Obsédée par Voldemort",
        "moralite": "Méchant",
        "famille": "Lestrange"
    },
    "Dolores Ombrage": {
        "maison": "Serpentard",
        "genre": "F",
        "cheveux": "Gris",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": True,
        "sang": "Pur",
        "role": "Professeur, inquisitrice",
        "trait_distinctif": "Porte toujours du rose",
        "moralite": "Méchant",
        "famille": "N/A"
    },
    "Cedric Diggory": {
        "maison": "Poufsouffle",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, champion du Tournoi",
        "trait_distinctif": "Tué par Queudver",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Cho Chang": {
        "maison": "Serdaigle",
        "genre": "F",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Inconnu",
        "role": "Élève, petite amie de Harry",
        "trait_distinctif": "Joueuse de Quidditch (attrapeur)",
        "moralite": "Gentil",
        "famille": "N/A"
    },
    "Peter Pettigrow": {
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Rat",
        "professeur": False,
        "sang": "Pur",
        "role": "Ancien ami de James Potter",
        "trait_distinctif": "Animagus (rat), traître",
        "moralite": "Méchant",
        "famille": "N/A"
    }
}
