caracteristiques_personnages = {

    "Harry Potter": {
        "description": "Un élève de Gryffondor aux cheveux noirs en bataille et aux lunettes rondes. Il est célèbre pour la cicatrice en forme d'éclair sur son front et son courage face à Voldemort.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Noirs",
        "lunettes": True,
        "baguette_particuliere": True,
        "animal": "Hibou",
        "professeur": False,
        "sang": "Mélé",
        "role": "Élève, héros",
        "trait_distinctif": "Cicatrice",
        "moralite": "Gentil",
        "famille": "Potter"
    },

    "Hermione Granger": {
        "description": "Une élève de Gryffondor aux cheveux bruns épais et bouclés. Brillante et très studieuse, elle ne porte pas de lunettes mais on la voit souvent avec un livre ou une baguette à la main.",
        "maison": "Gryffondor",
        "genre": "F",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Chat",
        "professeur": False,
        "sang": "Moldus",
        "role": "Élève, intelligente",
        "trait_distinctif": "Toujours un livre à la main",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Ron Weasley": {
        "description": "Un garçon aux cheveux roux caractéristiques de la famille Weasley. Élève de Gryffondor et meilleur ami de Harry, il a souvent l'air un peu maladroit mais fait preuve d'une grande loyauté.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Rat",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, ami de Harry",
        "trait_distinctif": "A peur des araignées",
        "moralite": "Gentil",
        "famille": "Weasley"
    },

    "Drago Malefoy": {
        "description": "Un élève de Serpentard aux cheveux blonds platine très clairs et au visage pâle. Toujours bien habillé avec sa cravate verte, il affiche souvent une expression arrogante ou méprisante.",
        "maison": "Serpentard",
        "genre": "H",
        "cheveux": "Blonds",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, rival de Harry",
        "trait_distinctif": "Père est un Mangemort",
        "moralite": "Méchant",
        "famille": "Malfoy"
    },

    "Luna Lovegood": {
        "description": "Une élève de Serdaigle aux très longs cheveux blonds ondulés. Elle a un style rêveur et excentrique, portant parfois des accessoires bizarres. Elle semble souvent être dans la lune.",
        "maison": "Serdaigle",
        "genre": "F",
        "cheveux": "Blonds",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Inconnu",
        "role": "Élève, excentrique",
        "trait_distinctif": "Croit aux créatures magiques invisibles",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Neville Londubat": {
        "description": "Un élève de Gryffondor aux cheveux bruns courts et aux dents un peu proéminentes. Souvent inquiet ou maladroit, il porte parfois son crapaud ou une plante magique.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Crapaud",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, timide",
        "trait_distinctif": "Devenu professeur de botanique",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Ginny Weasley": {
        "description": "Une jeune fille aux longs cheveux roux raides, typiques des Weasley. C'est une élève de Gryffondor, la plus jeune de sa famille, qui dégage une assurance calme.",
        "maison": "Gryffondor",
        "genre": "F",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, sœur de Ron",
        "trait_distinctif": "Joueuse de Quidditch (attrapeur)",
        "moralite": "Gentil",
        "famille": "Weasley"
    },

    "Fred Weasley": {
        "description": "L'un des jumeaux Weasley aux cheveux roux courts. Toujours souriant ou en train de rire, il porte l'uniforme de Gryffondor. Il est identique à son frère George.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Farceur, jumeau",
        "trait_distinctif": "Propriétaire de la boutique de farces",
        "moralite": "Gentil",
        "famille": "Weasley"
    },

    "George Weasley": {
        "description": "Le frère jumeau de Fred, avec les mêmes cheveux roux et le même uniforme de Gryffondor. Inséparable de son frère, il a l'air malicieux et prêt à faire une farce.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Roux",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Farceur, jumeau",
        "trait_distinctif": "A perdu une oreille",
        "moralite": "Gentil",
        "famille": "Weasley"
    },

    "Severus Rogue": {
        "description": "Un professeur aux cheveux noirs mi-longs, raides et gras. Il porte toujours des vêtements noirs et une longue cape sombre. Son expression est sévère et il dirige la maison Serpentard.",
        "maison": "Serpentard",
        "genre": "H",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": True,
        "sang": "Pur",
        "role": "Professeur, directeur",
        "trait_distinctif": "Ancien Mangemort, amoureux de Lily Potter",
        "moralite": "Ambigu",
        "famille": "N/A"
    },

    "Minerva McGonagall": {
        "description": "Une professeure âgée aux cheveux tirés en arrière, portant un chapeau pointu de sorcière et des lunettes carrées. Directrice de Gryffondor, elle a un air strict mais juste.",
        "maison": "Gryffondor",
        "genre": "F",
        "cheveux": "Noirs",
        "lunettes": True,
        "baguette_particuliere": True,
        "animal": "Chat",
        "professeur": True,
        "sang": "Pur",
        "role": "Professeur, directrice",
        "trait_distinctif": "Peut se transformer en chat",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Albus Dumbledore": {
        "description": "Un vieux sorcier avec une très longue barbe blanche et des cheveux argentés. Il porte des lunettes en demi-lune, un chapeau brodé et des robes majestueuses. C'est le directeur de Poudlard, ancien Gryffondor.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Argentés",
        "lunettes": True,
        "baguette_particuliere": True,
        "animal": "Phénix",
        "professeur": True,
        "sang": "Pur",
        "role": "Directeur de Poudlard",
        "trait_distinctif": "Aime les bonbons et les énigmes",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Rubeus Hagrid": {
        "description": "Un demi-géant immense avec une grosse barbe noire broussailleuse et des cheveux longs en désordre. Il porte un manteau épais en peau de bête et n'a pas d'uniforme scolaire. Ancien membre Gryffondor de Poudlard",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Noirs/barbe",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Chien",
        "professeur": True,
        "sang": "Mélé",
        "role": "Garde-chasse",
        "trait_distinctif": "Demi-géant, adore les créatures magiques",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Sirius Black": {
        "description": "Un homme aux cheveux foncés, longs et ondulés, portant souvent une moustache et une barbe. Il a l'air élégant mais fatigué par ses années de prison. C'est le parrain de Harry. Ami proche de James Potter, ancien Gryffondor.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Chien",
        "professeur": False,
        "sang": "Pur",
        "role": "Parrain de Harry",
        "trait_distinctif": "Animagus (chien noir)",
        "moralite": "Gentil",
        "famille": "Black"
    },

    "Remus Lupin": {
        "description": "Un homme aux cheveux châtains clairs et à la fine moustache, avec quelques cicatrices légères sur le visage. Il porte des vêtements souvent un peu usés et a un air bienveillant. Ami proche de James Potter, ancien Gryffondor.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": True,
        "sang": "Mélé",
        "role": "Professeur, loup-garou",
        "trait_distinctif": "Transformé en loup-garou",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Bellatrix Lestrange": {
        "description": "Une sorcière aux cheveux noirs longs, bouclés et très ébouriffés. Elle porte des vêtements noirs gothiques et a souvent une expression folle ou cruelle sur le visage. Ancienne Serpantard, elle va servir Voldemort avec passion.",
        "maison": "Serpentard",
        "genre": "F",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Mangemort",
        "trait_distinctif": "Obsédée par Voldemort",
        "moralite": "Méchant",
        "famille": "Lestrange"
    },

    "Dolores Ombrage": {
        "description": "Une petite femme aux cheveux châtains courts et bouclés. Elle porte presque toujours des vêtements entièrement roses (veste, chapeau) et a un sourire doucereux mais hypocrite. Ancienne élève de Serpantard",
        "maison": "Serpentard",
        "genre": "F",
        "cheveux": "Gris",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": True,
        "sang": "Pur",
        "role": "Professeur, inquisitrice",
        "trait_distinctif": "Porte toujours du rose",
        "moralite": "Méchant",
        "famille": "N/A"
    },

    "Cedric Diggory": {
        "description": "Un beau garçon aux cheveux châtains et aux yeux clairs. Il porte l'uniforme jaune et noir de Poufsouffle. Il a l'air athlétique et loyal.",
        "maison": "Poufsouffle",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève, champion du Tournoi",
        "trait_distinctif": "Tué par Queudver",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Cho Chang": {
        "description": "Une élève de Serdaigle aux longs cheveux noirs raides avec une frange. Elle porte la cravate bleue et bronze de sa maison et a un visage doux.",
        "maison": "Serdaigle",
        "genre": "F",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Inconnu",
        "role": "Élève, petite amie de Harry",
        "trait_distinctif": "Joueuse de Quidditch (attrapeur)",
        "moralite": "Gentil",
        "famille": "N/A"
    },

    "Peter Pettigrow": {
        "description": "Un petit homme rondouillard aux cheveux châtains filasses et aux dents de devant proéminentes, ressemblant un peu à un rat. Il a l'air craintif et sournois. Ancien ami de James Potter, ancien Gryffondor.",
        "maison": "Gryffondor",
        "genre": "H",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Rat",
        "professeur": False,
        "sang": "Pur",
        "role": "Ancien ami de James Potter",
        "trait_distinctif": "Animagus (rat), traître",
        "moralite": "Méchant",
        "famille": "N/A"
    },

    "Nymphadora Tonks": {
        "description": "Une jeune femme au style un peu punk, souvent vue avec des cheveux violets courts (bien qu'elle puisse changer de couleur). Elle ne porte pas l'uniforme scolaire. Ancienne élève de Pouffsouffle, elle va combattre voledemort en tant qu'auror.",
        "maison": "Poufsouffle",
        "genre": "F",
        "cheveux": "Variables (Métamorphomage)",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Mêlé",
        "role": "Auror, Ordre du Phénix",
        "trait_distinctif": "Métamorphomage",
        "moralite": "Gentil",
        "famille": "Tonks / Black (par alliance)"
    },

    "Padma Patil": {
        "description": "Une élève aux longs cheveux noirs foncés, souvent tressés ou attachés. Elle porte l'uniforme de Gryffondor (dans les films) et ressemble trait pour trait à sa jumelle Parvati.",
        "maison": "Gryffondor",
        "genre": "F",
        "cheveux": "Noirs",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève",
        "trait_distinctif": "Sœur jumelle de Parvati Patil",
        "moralite": "Gentil",
        "famille": "Patil"
    },

    "Pansy Parkinson": {
        "description": "Une élève de Serpentard aux cheveux noirs coupés au carré court avec une frange. Elle porte la cravate verte et reste souvent collée à Drago Malefoy.",
        "maison": "Serpentard",
        "genre": "F",
        "cheveux": "Bruns",
        "lunettes": False,
        "baguette_particuliere": False,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Pur",
        "role": "Élève",
        "trait_distinctif": "Proche de Draco Malfoy",
        "moralite": "Méchant",
        "famille": "Parkinson"
    },

    "Fleur Delacour": {
        "description": "Une jeune femme blonde très élégante portant l'uniforme bleu ciel en soie de l'école de Beauxbâtons, ainsi qu'un petit chapeau pointu bleu assorti.",
        "maison": "Beauxbâtons",
        "genre": "F",
        "cheveux": "Blonds",
        "lunettes": False,
        "baguette_particuliere": True,
        "animal": "Aucun",
        "professeur": False,
        "sang": "Part-Vélane",
        "role": "Champione de Beauxbâtons, future épouse de Bill Weasley",
        "trait_distinctif": "Part-Vélane (charme exceptionnel)",
        "moralite": "Gentil",
        "famille": "Delacour"
    }
}